export const piecesConstants = {
  BISHOP: 'BISHOP',
  KNIGHT: 'KNIGHT',
  UPDATE_AVAILABLE_MOVES: 'UPDATE_AVAILABLE_MOVES',
  UPDATE_PIECE_POSITION: 'UPDATE_PIECE_POSITION',
  SELECT_PIECE: 'SELECT_PIECE'

};
