export const squaresConstants = {
  RESET_SQUARES: 'RESET_SQUARES',
  HIGHLIGHT_AVAILABLE_SQUARES: 'HIGHLIGHT_AVAILABLE_SQUARES',
  HIDE_AVAILABLE_SQUARES: 'HIDE_AVAILABLE_SQUARES',
  ACCEPT_PIECE: 'ACCEPT_PIECE',
  SET_DRAG_TARGET: 'SET_DRAG_TARGET',
  CLEAR_DRAG_TARGET: 'CLEAR_DRAG_TARGET'
};
